spring.application.name=email_service
spring.docker.compose.enabled=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
app.rabbitmq.email-queue=email.queue

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gui.qlimasp@gmail.com
spring.mail.password=zrzz uyvy eozf xaxl

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=no-reply@onepilates.com
